trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
 
- script: dotnet build --configuration Release
  displayName: 'Build solution'
 
- script: dotnet test --configuration Release --no-build --verbosity normal
  displayName: 'Run unit tests'
 
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'your-azure-subscription'
    appType: 'webApp'
    appName: 'your-app-service-name'
    package: '$(System.DefaultWorkingDirectory)/drop/*.zip'